(() => {
  'use strict';
  const DATA = window.ARCHAEOLOGY_DATA;
  const STORAGE_KEY = 'archaeology-collections-alt1-v1';
  const number = new Intl.NumberFormat('en-GB', { maximumFractionDigits: 1 });
  const integer = new Intl.NumberFormat('en-GB', { maximumFractionDigits: 0 });
  const esc = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const keyFor = (collection, artifact) => `${collection.name}::${artifact.name}`;
  const emptyProgress = () => Object.fromEntries(DATA.collections.flatMap(c => c.artifacts.map(a => [keyFor(c,a), { damaged: 0, restored: 0 }])));
  const defaults = emptyProgress();
  let hasSavedProgress = false;
  let state = loadState();
  let selected = DATA.collections[0]?.name;
  let activeView = 'collections';
  let plannerCap = 98;

  function loadState(){try{const saved=localStorage.getItem(STORAGE_KEY);hasSavedProgress=Boolean(saved);return{...defaults,...JSON.parse(saved||'{}')}}catch{return{...defaults}}}
  function saveState(){const el=document.querySelector('#saveStatus');try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));hasSavedProgress=true;el.textContent='Saved in this browser at '+new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}catch{el.textContent='Browser storage is unavailable'}}
  function values(c,a){ return state[keyFor(c,a)] || {damaged:0,restored:0}; }
  function calcCollection(c){
    const owned=c.artifacts.map(a=>{const v=values(c,a);return v.damaged+v.restored});
    const sets=owned.length?Math.min(...owned):0;
    const materials={}; let xp=0, artifactChronotes=0, damaged=0, restored=0;
    c.artifacts.forEach(a=>{const v=values(c,a);damaged+=v.damaged;restored+=v.restored;xp+=v.damaged*a.xp;artifactChronotes+=v.restored*a.chronotes;Object.entries(a.materials).forEach(([m,q])=>materials[m]=(materials[m]||0)+q*v.damaged)});
    return {sets,materials,xp,artifactChronotes,setChronotes:sets*c.setBonus,chronotes:artifactChronotes+sets*c.setBonus,damaged,restored};
  }
  function totals(){
    const all={materials:{},xp:0,artifactChronotes:0,setChronotes:0,chronotes:0,damaged:0,restored:0,sets:0};
    DATA.collections.forEach(c=>{const x=calcCollection(c);Object.keys(all).filter(k=>k!=='materials').forEach(k=>all[k]+=x[k]);Object.entries(x.materials).forEach(([m,q])=>all.materials[m]=(all.materials[m]||0)+q)}); return all;
  }
  function completion(c){const done=c.artifacts.filter(a=>{const v=values(c,a);return v.damaged+v.restored>0}).length;return {done,total:c.artifacts.length,pct:c.artifacts.length?done/c.artifacts.length*100:0};}
  function filteredCollections(){const q=document.querySelector('#search').value.trim().toLowerCase();const group=document.querySelector('#groupFilter').value;return DATA.collections.filter(c=>(group==='all'||c.group===group)&&(!q||c.name.toLowerCase().includes(q)||c.artifacts.some(a=>a.name.toLowerCase().includes(q))));}
  function renderList(){const list=document.querySelector('#collectionList');const items=filteredCollections();if(!items.some(c=>c.name===selected))selected=items[0]?.name;list.innerHTML=items.length?items.map(c=>{const p=completion(c);return `<button class="collection-item ${c.name===selected?'active':''}" data-name="${esc(c.name)}"><span>${esc(c.name)}</span><small>${p.done}/${p.total} artefacts · ${integer.format(calcCollection(c).sets)} sets</small></button>`}).join(''):'<div class="empty">No results</div>';list.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.name;renderCollections()}));}
  function renderDetail(){const target=document.querySelector('#collectionDetail');const c=DATA.collections.find(x=>x.name===selected);if(!c){target.innerHTML='<div class="empty">Select a collection</div>';return}const x=calcCollection(c);const collectionMaterials=Object.entries(x.materials).filter(([,quantity])=>quantity>0).sort((a,b)=>b[1]-a[1]);target.innerHTML=`<div class="detail-head"><div><h2>${esc(c.name)}</h2><span class="badge">${esc(c.group)}</span></div></div><div class="metrics"><div class="metric"><span>Sets</span><strong>${integer.format(x.sets)}</strong></div><div class="metric"><span>Materials</span><strong>${integer.format(Object.values(x.materials).reduce((a,b)=>a+b,0))}</strong></div><div class="metric"><span>XP</span><strong>${integer.format(x.xp)}</strong></div><div class="metric"><span>Chronotes</span><strong>${integer.format(x.chronotes)}</strong></div></div><section class="collection-materials"><h3>Materials required for this collection</h3>${collectionMaterials.length?`<div class="material-chips">${collectionMaterials.map(([material,quantity])=>`<div class="material-chip"><span>${esc(material)}</span><strong>${integer.format(quantity)}</strong></div>`).join('')}</div>`:'<p class="materials-empty">Enter damaged artefact counts to calculate the materials required for this collection.</p>'}</section><div class="table-wrap"><table><thead><tr><th>Artefact</th><th class="num">Damaged</th><th class="num">Restored</th></tr></thead><tbody>${c.artifacts.map((a,i)=>{const v=values(c,a);const mats=Object.entries(a.materials).map(([m,q])=>`${q} ${esc(m)}`).join(' · ');return `<tr><td class="artifact-name"><strong>${esc(a.name)}</strong><div class="materials-inline">${mats} · ${number.format(a.xp)} XP · ${integer.format(a.chronotes)} chronotes</div></td><td class="num"><input class="qty" type="number" min="0" step="1" value="${v.damaged}" data-index="${i}" data-field="damaged" aria-label="Damaged: ${esc(a.name)}"></td><td class="num"><input class="qty" type="number" min="0" step="1" value="${v.restored}" data-index="${i}" data-field="restored" aria-label="Restored: ${esc(a.name)}"></td></tr>`}).join('')}</tbody></table></div><a class="source" href="${esc(c.source)}" target="_blank" rel="noreferrer">Open collection source ↗</a>`;target.querySelectorAll('.qty').forEach(input=>input.addEventListener('change',()=>{const a=c.artifacts[Number(input.dataset.index)];const v=values(c,a);v[input.dataset.field]=Math.max(0,Math.floor(Number(input.value)||0));state[keyFor(c,a)]=v;saveState();renderCollections();}));}
  function renderCollections(){renderList();renderDetail()}
  function renderMaterials(){const t=totals();const entries=Object.entries(t.materials).filter(([,q])=>q>0).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...entries.map(([,q])=>q));document.querySelector('#materialsContent').innerHTML=`<h2 class="section-title">All required materials</h2><div class="card"><span>Based on all damaged artefacts, matching the Excel workbook.</span></div><div class="table-wrap"><table><thead><tr><th>Material</th><th class="num">Quantity</th></tr></thead><tbody>${entries.length?entries.map(([m,q])=>`<tr><td>${esc(m)}<div class="material-bar"><i style="width:${q/max*100}%"></i></div></td><td class="num"><strong>${integer.format(q)}</strong></td></tr>`).join(''):'<tr><td colspan="2" class="empty">Enter damaged artefacts to calculate materials.</td></tr>'}</tbody></table></div>`;}
  function renderSummary(){const t=totals();const completed=DATA.collections.filter(c=>calcCollection(c).sets>0).length;document.querySelector('#summaryContent').innerHTML=`<h2 class="section-title">Overall summary</h2><div class="cards"><div class="card"><strong>${integer.format(t.xp)}</strong><span>Restoration XP</span></div><div class="card"><strong>${integer.format(t.xp*DATA.outfitMultiplier)}</strong><span>XP with outfit (+6%)</span></div><div class="card"><strong>${integer.format(t.chronotes)}</strong><span>Total chronotes</span></div><div class="card"><strong>${integer.format(t.sets)}</strong><span>Complete sets</span></div></div><div class="card"><table><tbody><tr><td>Chronotes from artefacts</td><td class="num">${integer.format(t.artifactChronotes)}</td></tr><tr><td>Chronotes from set bonuses</td><td class="num">${integer.format(t.setChronotes)}</td></tr><tr><td>Damaged artefacts</td><td class="num">${integer.format(t.damaged)}</td></tr><tr><td>Restored artefacts</td><td class="num">${integer.format(t.restored)}</td></tr><tr><td>Collections with at least one set</td><td class="num">${completed}/${DATA.collections.length}</td></tr></tbody></table></div>`;}
  function collectionMaxXp(c){return Math.max(0,...c.artifacts.map(a=>a.xp))}
  function planCandidates(cap){const xpCap=cap===99?17500:16666.7;return DATA.collections.filter(c=>collectionMaxXp(c)<=xpCap+.01).map(c=>({...c,artifactNames:new Set(c.artifacts.map(a=>a.name))}));}
  function optimisePlan(cap){
    const candidates=planCandidates(cap);const newlyUnlocked=cap===99?candidates.filter(c=>collectionMaxXp(c)>16666.71):[];let best=null;
    const seeds=newlyUnlocked.length?[null,...candidates.filter(c=>!newlyUnlocked.includes(c))]:candidates;
    seeds.forEach(seed=>{const chosen=[...newlyUnlocked];if(seed&&!chosen.includes(seed))chosen.push(seed);const unique=new Set(chosen.flatMap(c=>[...c.artifactNames]));while(chosen.length<25){const remaining=candidates.filter(c=>!chosen.includes(c));remaining.sort((a,b)=>{const aNew=[...a.artifactNames].filter(name=>!unique.has(name)).length;const bNew=[...b.artifactNames].filter(name=>!unique.has(name)).length;const aShared=a.artifactNames.size-aNew;const bShared=b.artifactNames.size-bNew;return aNew-bNew||bShared-aShared||a.artifacts.length-b.artifacts.length||b.setBonus-a.setBonus||a.name.localeCompare(b.name)});const next=remaining[0];if(!next)break;chosen.push(next);next.artifactNames.forEach(name=>unique.add(name));}const entries=chosen.reduce((sum,c)=>sum+c.artifacts.length,0);const score=unique.size*100000+entries*100-chosen.reduce((sum,c)=>sum+c.setBonus,0)/1000;if(chosen.length===25&&(!best||score<best.score))best={chosen,unique,entries,score};});return best;
  }
  function renderPlanner(){const plan=optimisePlan(plannerCap);document.querySelectorAll('.plan-toggle').forEach(button=>button.classList.toggle('active',Number(button.dataset.planCap)===plannerCap));if(!plan){document.querySelector('#plannerContent').innerHTML='<div class="empty">Not enough eligible collections for this level.</div>';return}const overlap=plan.entries-plan.unique.size;const sharedCount=c=>[...c.artifactNames].filter(name=>plan.chosen.some(other=>other!==c&&other.artifactNames.has(name))).length;const ordered=[...plan.chosen].sort((a,b)=>sharedCount(b)-sharedCount(a)||a.artifacts.length-b.artifacts.length||a.name.localeCompare(b.name));document.querySelector('#plannerContent').innerHTML=`<h2 class="section-title">Best 25 collection combination</h2><p class="plan-intro">Optimised for the fewest different artefact types and the most overlap between eligible collection logs. ${plannerCap===99?'The two Dragonkin I logs unlocked at level 99 are included.':'Only collections completable before level 99 are included.'}</p><div class="plan-summary"><div class="card"><strong>25</strong><span>Unique collections</span></div><div class="card"><strong>${integer.format(plan.entries)}</strong><span>Total artefact turn-ins</span></div><div class="card"><strong>${integer.format(plan.unique.size)}</strong><span>Different artefact types</span></div><div class="card"><strong>${integer.format(overlap)}</strong><span>Overlapping slots</span></div></div><div class="plan-list">${ordered.map((c,index)=>{const shared=sharedCount(c);const levelLabel=collectionMaxXp(c)>16666.71?'Level 99':'Under 99';return `<article class="plan-item"><span class="plan-rank">${index+1}</span><div><h3>${esc(c.name)}</h3><p>${c.artifacts.length} artefacts · ${shared} shared with this plan</p></div><span class="badge">${levelLabel}</span></article>`}).join('')}</div><p class="plan-note">Shared means the same artefact type occurs in multiple selected collections. You still need a separate restored copy for each collection turn-in.</p>`;}
  function showView(name){activeView=name;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector(`#${name}View`).classList.add('active');if(name==='collections')renderCollections();if(name==='materials')renderMaterials();if(name==='summary')renderSummary();if(name==='planner')renderPlanner();}
  function exportState(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),progress:state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='archaeology-collections-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function resetProgress(){localStorage.removeItem(STORAGE_KEY);state=emptyProgress();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));showView(activeView);document.querySelector('#saveStatus').textContent='All artefact counts are 0';}
  document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  document.querySelectorAll('.plan-toggle').forEach(button=>button.addEventListener('click',()=>{plannerCap=Number(button.dataset.planCap);renderPlanner()}));
  document.querySelector('#collectionDetail').addEventListener('input',event=>{const input=event.target.closest('.qty');if(!input)return;const c=DATA.collections.find(item=>item.name===selected);const a=c?.artifacts[Number(input.dataset.index)];if(!c||!a)return;const v=values(c,a);v[input.dataset.field]=Math.max(0,Math.floor(Number(input.value)||0));state[keyFor(c,a)]=v;saveState();});
  document.querySelector('#search').addEventListener('input',renderCollections);document.querySelector('#groupFilter').addEventListener('change',renderCollections);document.querySelector('#exportBtn').addEventListener('click',exportState);
  document.querySelector('#importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());state={...defaults,...(parsed.progress||parsed)};saveState();showView(activeView)}catch{alert('This is not a valid progress export.')}e.target.value='';});
  document.querySelector('#resetBtn').addEventListener('click',resetProgress);
  const install=document.querySelector('#installBtn');if(window.alt1&&install){const configUrl='https://archeology-collections.fun/dist/appconfig.json';install.hidden=false;try{window.alt1.identifyAppUrl(configUrl)}catch{}install.addEventListener('click',()=>{try{window.alt1.identifyAppUrl(configUrl)}catch{}})}
  renderCollections();
  if(hasSavedProgress)document.querySelector('#saveStatus').textContent='Progress loaded from this browser';
})();
