(() => {
  'use strict';
  const DATA = window.ARCHAEOLOGY_DATA;
  const STORAGE_KEY = 'archaeology-collections-alt1-v1';
  const number = new Intl.NumberFormat('en-GB', { maximumFractionDigits: 1 });
  const integer = new Intl.NumberFormat('en-GB', { maximumFractionDigits: 0 });
  const esc = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const keyFor = (collection, artifact) => `${collection.name}::${artifact.name}`;
  const emptyProgress = () => Object.fromEntries(DATA.collections.flatMap(c => c.artifacts.map(a => [keyFor(c,a), { damaged: 0, restored: 0 }])));
  const defaults = emptyProgress();
  let state = loadState();
  let selected = DATA.collections[0]?.name;
  let activeView = 'collections';

  function loadState(){ try { return { ...defaults, ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}') }; } catch { return { ...defaults }; } }
  function saveState(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); const el=document.querySelector('#saveStatus'); el.textContent='Saved at '+new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}); }
  function values(c,a){ return state[keyFor(c,a)] || {damaged:0,restored:0}; }
  function calcCollection(c){
    const owned=c.artifacts.map(a=>{const v=values(c,a);return v.damaged+v.restored});
    const sets=owned.length?Math.min(...owned):0;
    const materials={}; let xp=0, artifactChronotes=0, damaged=0, restored=0;
    c.artifacts.forEach(a=>{const v=values(c,a);damaged+=v.damaged;restored+=v.restored;xp+=v.damaged*a.xp;artifactChronotes+=v.restored*a.chronotes;Object.entries(a.materials).forEach(([m,q])=>materials[m]=(materials[m]||0)+q*v.damaged)});
    return {sets,materials,xp,artifactChronotes,setChronotes:sets*c.setBonus,chronotes:artifactChronotes+sets*c.setBonus,damaged,restored};
  }
  function totals(){
    const all={materials:{},xp:0,artifactChronotes:0,setChronotes:0,chronotes:0,damaged:0,restored:0,sets:0};
    DATA.collections.forEach(c=>{const x=calcCollection(c);Object.keys(all).filter(k=>k!=='materials').forEach(k=>all[k]+=x[k]);Object.entries(x.materials).forEach(([m,q])=>all.materials[m]=(all.materials[m]||0)+q)}); return all;
  }
  function completion(c){const done=c.artifacts.filter(a=>{const v=values(c,a);return v.damaged+v.restored>0}).length;return {done,total:c.artifacts.length,pct:c.artifacts.length?done/c.artifacts.length*100:0};}
  function filteredCollections(){const q=document.querySelector('#search').value.trim().toLowerCase();const group=document.querySelector('#groupFilter').value;return DATA.collections.filter(c=>(group==='all'||c.group===group)&&(!q||c.name.toLowerCase().includes(q)||c.artifacts.some(a=>a.name.toLowerCase().includes(q))));}
  function renderList(){const list=document.querySelector('#collectionList');const items=filteredCollections();if(!items.some(c=>c.name===selected))selected=items[0]?.name;list.innerHTML=items.length?items.map(c=>{const p=completion(c);return `<button class="collection-item ${c.name===selected?'active':''}" data-name="${esc(c.name)}"><span>${esc(c.name)}</span><small>${p.done}/${p.total} artefacts · ${integer.format(calcCollection(c).sets)} sets</small></button>`}).join(''):'<div class="empty">No results</div>';list.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.name;renderCollections()}));}
  function renderDetail(){const target=document.querySelector('#collectionDetail');const c=DATA.collections.find(x=>x.name===selected);if(!c){target.innerHTML='<div class="empty">Select a collection</div>';return}const x=calcCollection(c);const collectionMaterials=Object.entries(x.materials).filter(([,quantity])=>quantity>0).sort((a,b)=>b[1]-a[1]);target.innerHTML=`<div class="detail-head"><div><h2>${esc(c.name)}</h2><span class="badge">${esc(c.group)}</span></div></div><div class="metrics"><div class="metric"><span>Sets</span><strong>${integer.format(x.sets)}</strong></div><div class="metric"><span>Materials</span><strong>${integer.format(Object.values(x.materials).reduce((a,b)=>a+b,0))}</strong></div><div class="metric"><span>XP</span><strong>${integer.format(x.xp)}</strong></div><div class="metric"><span>Chronotes</span><strong>${integer.format(x.chronotes)}</strong></div></div><section class="collection-materials"><h3>Materials required for this collection</h3>${collectionMaterials.length?`<div class="material-chips">${collectionMaterials.map(([material,quantity])=>`<div class="material-chip"><span>${esc(material)}</span><strong>${integer.format(quantity)}</strong></div>`).join('')}</div>`:'<p class="materials-empty">Enter damaged artefact counts to calculate the materials required for this collection.</p>'}</section><div class="table-wrap"><table><thead><tr><th>Artefact</th><th class="num">Damaged</th><th class="num">Restored</th></tr></thead><tbody>${c.artifacts.map((a,i)=>{const v=values(c,a);const mats=Object.entries(a.materials).map(([m,q])=>`${q} ${esc(m)}`).join(' · ');return `<tr><td class="artifact-name"><strong>${esc(a.name)}</strong><div class="materials-inline">${mats} · ${number.format(a.xp)} XP · ${integer.format(a.chronotes)} chronotes</div></td><td class="num"><input class="qty" type="number" min="0" step="1" value="${v.damaged}" data-index="${i}" data-field="damaged" aria-label="Damaged: ${esc(a.name)}"></td><td class="num"><input class="qty" type="number" min="0" step="1" value="${v.restored}" data-index="${i}" data-field="restored" aria-label="Restored: ${esc(a.name)}"></td></tr>`}).join('')}</tbody></table></div><a class="source" href="${esc(c.source)}" target="_blank" rel="noreferrer">Open collection source ↗</a>`;target.querySelectorAll('.qty').forEach(input=>input.addEventListener('change',()=>{const a=c.artifacts[Number(input.dataset.index)];const v=values(c,a);v[input.dataset.field]=Math.max(0,Math.floor(Number(input.value)||0));state[keyFor(c,a)]=v;saveState();renderCollections();}));}
  function renderCollections(){renderList();renderDetail()}
  function renderMaterials(){const t=totals();const entries=Object.entries(t.materials).filter(([,q])=>q>0).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...entries.map(([,q])=>q));document.querySelector('#materialsContent').innerHTML=`<h2 class="section-title">All required materials</h2><div class="card"><span>Based on all damaged artefacts, matching the Excel workbook.</span></div><div class="table-wrap"><table><thead><tr><th>Material</th><th class="num">Quantity</th></tr></thead><tbody>${entries.length?entries.map(([m,q])=>`<tr><td>${esc(m)}<div class="material-bar"><i style="width:${q/max*100}%"></i></div></td><td class="num"><strong>${integer.format(q)}</strong></td></tr>`).join(''):'<tr><td colspan="2" class="empty">Enter damaged artefacts to calculate materials.</td></tr>'}</tbody></table></div>`;}
  function renderSummary(){const t=totals();const completed=DATA.collections.filter(c=>calcCollection(c).sets>0).length;document.querySelector('#summaryContent').innerHTML=`<h2 class="section-title">Overall summary</h2><div class="cards"><div class="card"><strong>${integer.format(t.xp)}</strong><span>Restoration XP</span></div><div class="card"><strong>${integer.format(t.xp*DATA.outfitMultiplier)}</strong><span>XP with outfit (+6%)</span></div><div class="card"><strong>${integer.format(t.chronotes)}</strong><span>Total chronotes</span></div><div class="card"><strong>${integer.format(t.sets)}</strong><span>Complete sets</span></div></div><div class="card"><table><tbody><tr><td>Chronotes from artefacts</td><td class="num">${integer.format(t.artifactChronotes)}</td></tr><tr><td>Chronotes from set bonuses</td><td class="num">${integer.format(t.setChronotes)}</td></tr><tr><td>Damaged artefacts</td><td class="num">${integer.format(t.damaged)}</td></tr><tr><td>Restored artefacts</td><td class="num">${integer.format(t.restored)}</td></tr><tr><td>Collections with at least one set</td><td class="num">${completed}/${DATA.collections.length}</td></tr></tbody></table></div>`;}
  function showView(name){activeView=name;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector(`#${name}View`).classList.add('active');if(name==='collections')renderCollections();if(name==='materials')renderMaterials();if(name==='summary')renderSummary();}
  function exportState(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),progress:state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='archaeology-collections-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function resetProgress(){localStorage.removeItem(STORAGE_KEY);state=emptyProgress();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));showView(activeView);document.querySelector('#saveStatus').textContent='All artefact counts are 0';}
  document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  document.querySelector('#search').addEventListener('input',renderCollections);document.querySelector('#groupFilter').addEventListener('change',renderCollections);document.querySelector('#exportBtn').addEventListener('click',exportState);
  document.querySelector('#importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());state={...defaults,...(parsed.progress||parsed)};saveState();showView(activeView)}catch{alert('This is not a valid progress export.')}e.target.value='';});
  document.querySelector('#resetBtn').addEventListener('click',resetProgress);
  const install=document.querySelector('#installBtn');if(window.alt1){const configUrl='https://vbijvoets.github.io/Archeology-plugin/dist/appconfig.json';install.hidden=false;try{window.alt1.identifyAppUrl(configUrl)}catch{}install.addEventListener('click',()=>{try{window.alt1.identifyAppUrl(configUrl)}catch{}})}
  renderCollections();
})();
